server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Workspace/Projects/Swifttdial/new/be/configurations-repository
          clone-on-start: true
  security:
    user:
      name: syhos-app
      password: )2P?dE=rB<y;S6Sv

# encrypt.key-store.location=classpath:/config-server.jks
# encrypt.key-store.password=my-s70r3-s3cr3t
# encrypt.key-store.alias=config-server-key
# encrypt.key- store.secret=my-k34-s3cr3t