spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Swiftt-Dial/configurations.git
          clone-on-start: true
          username: gathigai@gmail.com
          password: GiT#iicdinicdit#1