const DOMAIN = 'http://34.121.219.244';
const PORT = ':8081';
const API_VERSION = '/api/v1';
const API_URL = DOMAIN + PORT + API_VERSION;

module.exports = {
  name: 'Swifttdial v0.1',
  prefix: 'swifttdial',
  footerText: 'Swifttdial All Rights Reserved 2020',
  logoSrc: 'assets/syhos-logo.svg',
  logoText: 'Swifttdial',
  needLogin: true,
  API_URL,
  api: {
    accessControl: {
      privileges: '/privileges',
      profile: '/profile',
      profileActions: '/profile/actions',
      role: '/roles/:publicId',
      roleActions: '/roles/:publicId/actions',
      privilegesByRole: '/roles/:publicId/privileges',
      roles: '/roles',
      users: '/users',
      user: '/users/:publicId',
      userActions: '/users/:publicId/actions',
      userIdentifications: '/users/:publicId/userIdentifications',
      userIdentification: '/users/:userPublicId/userIdentifications/:publicId',
      userRoles: '/users/:userPublicId/roles',
      userRole: '/users/:userPublicId/roles/:publicId',
      userSpecializations: '/users/:userPublicId/userSpecializations',
      userSpecialization: '/users/:userPublicId/userSpecializations/:publicId',
      usersImport: '/import/users',
      usersByRole: '/roles/:publicId/users',
      userGroups: '/actors',
      userGroup: '/actors/:publicId',
      userGroupSpecializations: '/actors/:publicId/userSpecializations',
    },
    accounting: {
      accountingPreferences: '/accountingPreferences',
      accountingPreference: '/accountingPreferences/:publicId',
      accounts: '/accounts',
      account: '/accounts/:publicId',
      accountActions: '/accounts/:publicId/actions',
      bankReconciliations: '/bankReconciliations',
      bankReconciliation: '/bankReconciliations/:id',
      bankReconciliationActions: '/bankReconciliations/:id/actions',
      chargeTypes: '/chargeTypes',
      chargeType: '/chargeTypes/:publicId',
      contacts: '/contacts',
      contact: '/contacts/:publicId',
      contactIdentifications: '/contacts/:contactId/identifications',
      contactIdentification: '/contacts/:contactId/identifications/:publicId',
      contactPersons: '/contacts/:contactId/contactPersons',
      contactPerson: '/contacts/:contactId/contactPersons/:publicId',
      creditNotes: '/creditNotes',
      creditNote: '/creditNotes/:id',
      creditNoteActions: '/creditNotes/:id/actions',
      customerCategories: '/customerCategories',
      customerCategory: '/customerCategories/:id',
      customerInvoices: '/customerInvoices',
      customerInvoice: '/customerInvoices/:id',
      customerPayments: '/customerPayments',
      customerPayment: '/customerPayments/:id',
      customerPaymentsActions: '/customerPayments/:id/actions',
      debitNotes: '/debitNotes',
      debitNote: '/debitNotes/:id',
      debitNoteActions: '/debitNotes/:id/actions',
      currencies: '/currencies',
      deductionTypes: '/deductionTypes',
      deductionType: '/deductionTypes/:publicId',
      depositDefinitions: '/depositDefinitions',
      depositDefinition: '/depositDefinitions/:publicId',
      paymentTerms: '/paymentTerms',
      paymentTerm: '/paymentTerms/:publicId',
      vendorCategories: '/vendorCategories',
      vendorCategory: '/vendorCategories/:id',
      schemes: '/schemes',
      scheme: '/schemes/:publicId',
      taxTypes: '/taxTypes',
      taxType: '/taxTypes/:publicId',
      taxCodes: '/taxCodes',
      taxCode: '/taxCodes/:id',
      tradingCurrencies: '/tradingCurrencies',
      tradingCurrency: '/tradingCurrencies/:publicId',
      tradingCurrencyRateHistory: '/tradingCurrencies/:publicId/history',
      vendorBills: '/vendorBills',
      vendorBill: '/vendorBills/:id',
      vendorBillActions: '/vendorBills/:id/actions',
      vendorPayments: '/vendorPayments',
      vendorPayment: '/vendorPayments/:id',
      vendorPaymentActions: '/vendorPayments/:id/actions',
      paymentModes: '/paymentModes',
      paymentMode: '/paymentModes/:publicId',
      printAccountListings: '/export/accountListings',
      journals: {
        customerRefundEntries: '/customerRefunds',
        journalEntries: '/journals',
        manualJournalEntries: '/manualEntries',
        manualEntriesLines: '/manualEntries/:id/lines',
        bankingEntries: '/bankingEntries',
        bankingEntriesLines: '/bankingEntries/:id/lines',
        pettyCashEntries: '/pettyCashEntries',
        pettyCashEntriesLines: '/pettyCashEntries/:id/lines',
        customerInvoices: '/customerInvoices',
        customerInvoicesLines: '/customerInvoices/:id/lines',
      },
      reports: {
        balanceSheetDetail: '/reports/balanceSheet',
        balanceSheetExport: '/export/balanceSheet',
        balanceSheetSummary: '/reports/balanceSheetSummary',
        balanceSheetSummaryExport: '/export/balanceSheetSummary',
        cashBook: '/reports/cashBook',
        cashiersCollectionSummary: '/reports/cashiersCollectionSummary',
        cashierCollectionAnalysis: '/reports/cashierCollectionAnalysis',
        customerStatement: '/reports/customerStatement',
        customerAging: '/reports/customerAging',
        vendorStatement: '/reports/vendorStatement',
        vendorAging: '/reports/vendorAging',
        generalLedger: '/reports/generalLedger',
        incomeStatementSummary: '/reports/incomeStatementSummary',
        incomeStatementDetail: '/reports/incomeStatement',
        trialBalance: '/reports/trialBalance',
        trialBalanceGroups: '/reports/trialBalanceGroups',
      },
    },
    admissions: '/admissions',
    admission: '/admissions/:id',
    admissionActions: '/admissions/:id/actions',
    appointments: '/appointments',
    appointment: '/appointments/:id',
    appointmentActions: '/appointments/:id/actions',
    authentication: {
      userLogin: '/uaa/oauth/authorization',
      userLogout: '/user/logout',
    },
    beds: '/beds',
    bed: '/beds/:id',
    billing: {
      billingGroups: '/billingGroups',
      billingGroup: '/billingGroups/:id',
      billingRules: '/billingRules',
      billingRule: '/billingRules/:id',
      deposits: '/deposits',
      deposit: '/deposits/:id',
      depositActions: '/deposits/:id/actions',
      depositRequests: '/depositRequests',
      depositRequest: '/depositRequests/:id',
      walletTypes: '/walletTypes',
      walletType: '/walletTypes/:publicId',
      requests: '/visits/:encounterId/requests',
      requestItemsActions: '/requests/:requestId/actions',
      bills: '/bills',
      visitBillItems: '/visits/:visitId/billItems',
      billsByItemType: '/bills/search/byItemType',
      visitActions: '/visits/:visitId/actions',
      salesReceipts: '/customerSalesReceipts',
      salesReceipt: '/customerSalesReceipts/:saleReceiptId',
      invoices: '/customerInvoices',
      invoiceDetails: '/customerInvoices/:customerInvoiceId',
      printInvoice: '/export/invoices/',
      printReceipt: '/export/salesReceipts',
    },
    fixed_asset : {
      assets : '/fixedAssets',
      asset : '/fixedAssets/:id',

      assetActions: '/fixedAssets/:id/assetActions',
      assetWarranties: '/fixedAssets/:id/assetWarranties',
      assetInsurances: '/fixedAssets/:id/assetInsurances',
      insurance : '/fixedAssetsInsurance/:id',
      warranty : '/fixedAssetsWarranty/:id',

      categories : '/fixedAssetCategories',
      category : '/fixedAssetCategories/:id',
      categoryActions: '/fixedAssetCategories/:id/categoryActions',

      maintenances : '/fixedAssetMaintenances',
      maintenance : '/fixedAssetMaintenances/:id',
      maintenanceCategories : '/fixedAssetMaintenanceCategories',
      maintenanceCategory : '/fixedAssetMaintenanceCategories/:id',
      maintenanceCategoryActions: '/fixedAssetMaintenanceCategories/:id/categoryActions',

      transfers : '/fixedAssetTransfers',
      transfer : '/fixedAssetTransfers/:id',
      transferActions: '/fixedAssetTransfers/:id/actions',

      disposals : '/fixedAssetDisposals',
      disposal : '/fixedAssetDisposals/:id',
      disposalActions: '/fixedAssetDisposals/:id/actions',

      //stockTakes : '/fixedAssetStocktakes',
      //stockTake : '/fixedAssetStocktakes/:id',
      stockTakeLists: '/fixedAssetStocktakes',
      stockTakeList: '/fixedAssetStocktakes/:id',
      stockTakeListActions: '/fixedAssetStocktakes/:id/actions',

      adjustments : '/fixedAssetAdjustments',
      adjustment : '/fixedAssetAdjustments/:id',

    },
    catalogue: {
      groups: '/groups',
      group: '/groups/:id',
      groupActions: '/groups/:id/actions',
      formulations: '/formulations',
      formulation: '/formulations/:id',
      strengths: '/strengths',
      strength: '/strengths/:id',
      activeIngredients: '/activeIngredients',
      activeIngredient: '/activeIngredients/:id',
      administrationRoutes: '/administrationRoutes',
      administrationRoute: '/administrationRoutes/:id',
      manufacturers: '/manufacturers',
      manufacturer: '/manufacturers/:id',
      brands: '/brands',
      brand: '/brands/:id',
      products: '/products',
      product: '/products/:id',
      productsImport: '/import/products',
      productActions: '/products/:id/actions',
      prices: '/prices',
      price: '/prices/:id',
      priceDeductions: '/prices/:id/deductions',
      priceDeduction: '/prices/:priceId/deductions/:id',
      priceLists: '/priceLists',
      priceList: '/priceLists/:id',
      priceListActions: '/priceLists/:priceListId/actions',
      unitsOfMeasure: '/unitsOfMeasure',
      unitOfMeasure: '/unitsOfMeasure/:id',
    },
    contactsImport: '/import/contacts',
    countries: '/countries',
    departments: '/departments',
    department: '/departments/:publicId',
    diagnosesImport: '/import/diagnosesImport',
    diagnoses: '/diagnoses',
    diagnosisVersions: '/diagnosisVersions',
    diagnosisVersion: '/diagnosisVersions/:id',
    exportDocuments: {
      purchaseOrderPdf: '/export/purchaseOrders',
    },
    encounterProfile: {
      encounter: '/visits/:id',
      encounters: '/visits',
      encounterActions: '/visits/:encounterId/actions',
      encounterDischargeSummaries: '/visits/:encounterId/dischargeSummaries',
      encounterNotes: '/visits/:encounterId/notes',
      encounterNote: '/visits/:encounterId/notes/:id',
      encounterDiagnoses: '/visits/:encounterId/diagnoses',
      encounterDiagnosis: '/visits/:encounterId/diagnoses/:diagnosisId',
      medications: '/visits/:encounterId/medications',
      medication: '/visits/:encounterId/medications/:id',
      medicalSupplies: '/visits/:encounterId/medicalSupplies',
      medicalSupply: '/visits/:encounterId/medicalSupplies/:id',
      requests: '/visits/:encounterId/requests',
      request: '/visits/:encounterId/requests/:requestId',
      requestItemsByEncounter: '/visits/:encounterId/requestItems',
    },
    files: '/files',
    file: '/files/:id',
    folders: '/folders',
    folder: '/folders/:id',
    identificationType: '/identificationTypes/:publicId',
    identificationTypes: '/identificationTypes',
    institutions: '/institutions',
    institution: '/institutions/:publicId',
    inventory: {
      binLocations: '/binLocations',
      binLocation: '/binLocations/:publicId',
      goodsReturns: '/goodsReturns',
      goodsReturn: '/goodsReturns/:id',
      goodsReturnActions: '/goodsReturns/:id/actions',
      goodsReturnReasons: '/goodsReturnReasons',
      goodsReturnReason: '/goodsReturnReasons/:id',
      inventoryAdjustments: '/inventoryAdjustments',
      inventoryAdjustment: '/inventoryAdjustments/:id',
      inventoryAdjustmentActions: '/inventoryAdjustments/:id/actions',
      inventoryAdjustmentReasons: '/inventoryAdjustmentReasons',
      inventoryAdjustmentReason: '/inventoryAdjustmentReasons/:id',
      inventoryBalances: {
        detailed: '/inventoryBalances/detailed',
        summarized: '/inventoryBalances/summarized',
      },
      inventoryBalanceThresholds: '/inventoryBalanceThresholds',
      inventoryExpiries: '/inventoryExpiries',
      inventoryMetadata: '/inventoryMetadata',
      inventoryMetadataActions: '/inventoryMetadata/:product/actions',
      inventoryPreferences: '/inventoryPreferences',
      inventoryPreference: '/inventoryPreferences/:id',
      inventoryTransactions: '/inventoryTransactions',
      reorderLevels: '/reorderLevels',
      reorderLevel: '/reorderLevels/:id',
      inventoryTransfers: '/inventoryTransfers',
      inventoryTransfer: '/inventoryTransfers/:id',
      inventoryTransferActions: '/inventoryTransfers/:id/actions',
      stockTakeLists: '/stockTakeLists',
      stockTakeList: '/stockTakeLists/:id',
      stockTakeListActions: '/stockTakeLists/:id/actions',
    },
    journalsImport: '/import/journals',
    locations: '/locations',
    location: '/locations/:publicId',
    locationTypes: '/locationTypes',
    locationType: '/locationTypes/:publicId',
    me: {
      myInstitution: '/institutions/me',
    },
    medicalRecords: {
      appointmentTypes: '/appointmentTypes',
      appointmentType: '/appointmentTypes/:id',
      dischargeDispositions: '/dischargeDispositions',
      dischargeDisposition: '/dischargeDispositions/:id',
      handOverReasons: '/handOverReasons',
      handOverReason: '/handOverReasons/:id',
      specimens: '/specimens',
      specimen: '/specimens/:id',
      templates: '/templates',
      template: '/templates/:id',
      requestInvestigations: '/requests/:requestId/requestItems/:requestItemId/investigations',
      visitInvestigation: '/visits/:encounterId/investigations',
      actions: '/requests/:requestId/requestItems/:requestItemId/actions',
      triageCategories: '/triageCategories',
      triageCategory: '/triageCategories/:id',
      visitTypes: '/visitTypes',
      visitType: '/visitTypes/:id',
      arrivalMeans: '/meansOfArrival',
      arrivalMean: '/meansOfArrival/:id',
      medicoLegals: '/medicalJurisprudences',
      medicoLegal: '/medicalJurisprudences/:id',
    },
    objects: '/objects',
    object: '/object/:publicId',
    objectTypes: '/objectTypes',
    objectType: '/objectTypes/:publicId',
    organogramNodes: '/organogramNodes',
    organogramNode: '/organogramNodes/:publicId',
    outboundChannels: '/outboundChannels',
    outboundChannel: '/outboundChannels/:publicId',
    patients: '/patients',
    patientsImport: '/import/patients',
    patientProfile: {
      patient: '/patients/:id',
      encounters: '/patients/:patientId/visits',
      medicalHistoryEntries: '/patients/:patientId/medicalHistoryEntries',
      medicalHistoryEntry: '/patients/:patientId/medicalHistoryEntries/:id',
      paymentWallets: '/patients/:patientId/wallets',
      patientPreferences: '/patients/:patientId/preferences',
      patientPreferencesEntry: '/patients/:patientId/preferences/:id',
      guardians:'/patients/:patientId/guardians',
      guardian:'/patients/:patientId/guardians/:guardianId'
    },
    procurement: {
      purchaseItems: '/purchaseItems',
      purchaseItem: '/purchaseItems/:id',
      purchaseOrders: '/purchaseOrders',
      purchaseOrder: '/purchaseOrders/:id',
      purchaseOrderActions: '/purchaseOrders/:id/actions',
      receiptNotes: '/receiptNotes',
      receiptNote: '/receiptNotes/:id',
      receiptNoteGoodsReturns: '/receiptNotes/:id/goodsReturns',
      receiptNoteActions: '/receiptNotes/:id/actions',
      requisitions: '/requisitions',
      requisition: '/requisitions/:id',
      requisitionActions: '/requisitions/:id/actions',
    },
    queue: {
      requests: '/requests',
      req: '/requests/:id',
      requestActions: '/requests/:id/actions',
      requestItem: '/requestItems/:id',
      requestItemActions: '/requestItems/:id/actions',
      requestItems: '/requests/:id/requestItems',
    },
    countPatients: '/patients/action/countNewToday',
    regions: '/regions',
    region: '/regions/:publicId',
    religions: '/religions',
    religion: '/religions/:publicId',
    standardsPreferences: '/standardsPreferences',
    standardsPreference: '/standardsPreferences/:id',
    titles: '/titles',
    title: '/titles/:publicId',
    userProfile: {
      biometrics: '/users/:userPublicId/fingerprints',
      nextOfKins: '/users/:userId/nextOfKins',
      nextOfKin: '/users/:userId/nextOfKins/:publicId',
    },
    wards: '/wards',
    ward: '/wards/:publicId',
    calls: '/calls',
    call: '/calls/:publicId',
    ivrOptions: '/ivrOptions',
    ivrOption: '/ivrOptions/:publicId'
  },
  dev: {
    clientId: 'syhos-web-ui',
    clientSecret: 'bCc-_?Wv5g%v8Zk?uXm+VRR69v-FbKtKQqwy@SfuA3qnemJEfzFG3wA7d3v5C9X#UKJ3@Rda&aWeP8urR4D@f2BKNDE88t&tJmR7n#@HSG#tS5bp&9ECy_w^qERZfSFK@e?4SebC&#gnXQ&g#C-R=yF4YsSXLRJZLUyhRvPY%FmmyuH3wg?2U$d#6?txLe2LG4V!c8!CbGC9MQzUWfU5uwq^aZyXkA*_jJ+gK^uAu7v#B?RxckdJw=j!QW^_A2B*',
    grantType: 'password',
  },
  qa: {},
  production: {},
};
